version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "devops-frontend"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - npm run build
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
discard-paths: yes
